name: Generate GitHub Stats
on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Stats
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          card: stats
          options: username=Varun-ai07&show_icons=true&theme=radical&hide_border=true&bg_color=0D1117&title_color=F85D7F&icon_color=F8D866
          path: profile/stats.svg

      - name: Generate Languages
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          card: top-langs
          options: username=Varun-ai07&layout=compact&theme=radical&hide_border=true&bg_color=0D1117&title_color=F85D7F
          path: profile/langs.svg

      - name: Commit & Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add profile/*.svg
          git commit -m "Update GitHub stats" || exit 0
          git push
